lowhook03/42_Minishell

testcodes/test.c

포크한 레포에 변경사항 푸쉬하여 원본 레포에 풀 리퀘스트 테스트

[Test] : changed test.c

---

testcodes/basic_execution_structure.c

말 그대로 아주 대충 기본적인 실행부의 큰 틀 만들어봤습니다.

Test : 대충 짜본 기본 실행구조 - jincpark

---

Project_Dir/includes/data.h

커맨드, 환경변수 등 프로세스 실행을 위한 정보를 담을 구조체를 생성했습니다.

Feat : data.h 추가 > 실행을 위한 구조체 생성 - jincpark

---

parser/grammar_rules
parser/minishell_grammar

Shell 문법에서 simple command 부분만 추려내어 간략화 하였습니다.

minishell 문법 완성, 필요한 규칙 문서 추가

---

testcodes/parser_make_struct.c

문법이 맞았을 때, 구조체 배열을 만들 수 있는 구조 형성

Test : parser_make_struct

---

Project_Dir/parse.c
parser/minishell_grammar

왼쪽재귀로 문법 수정
BNF 룰에 따라 파서 추가 구현 중

문법 수정 및 재귀하향파서 추가 구현

---

Project_Dir/parse.c

재귀적 실행을 고려했을 때 lst_prepend 가 아닌 lst_append가 맞다는 것을 깨달았습니다..

Feat : proc_data prepend에서 append로 수정 - jincpark

---

Project_Dir/includes/data.h

Fix : fixed structure of t_data, t_proc_data - jincpark

---

Project_Dir/srcs/parse/parse.c

suffix 혹은 prefix가 없을 경우 판별 조건문 수정 및 word가 와야 할 자리에 redirection 올 경우 판별 조건 parse_cmd_word()로 이동

Feat : changed parse_suffix() & parse_prefix() - jincpark

---

testcodes/built_in.c

Test : Built_in.c

---

Project_Dir/libraries/libft/src/ft_free.c

인자를 싱글포인터에서 더블포인터로 받아서 댕글링포인터 처리할 수 있도록 했습니다.

Feat : changed ft_free() for handling a dangling pointer - jincpark

---

Project_Dir/libraries/dllist/src/list_delete.c

ft_free()가 더블포인터를 받도록 구조가 바뀌어서 lst_delete 관련 함수들 내부 변수들을 수정했습니다.

Feat : changed lst_delete funcs by fixed ft_free() - jincpark

---

Project_Dir/includes/data.h

Feat : added syntax error flag in s_data - jincpark

---

Project_Dir/libraries/dllist/src/list_delete.c

관련 함수들이 더블포인터를 인자로 받는 함수 포인터를  받도록 하였습니다.

Feat : list_delete funcs fix - jincpark

---

Project_Dir/srcs/parse/syntax_err.c

syntax err 시 토큰리스트, 커맨드리스트,, 리다이렉션리스트, 프로세스데이터리스트 삭제 및 프리 구현

Feat : del_s_token(), del_s_cmd(), del_s_ridir(), del_proc_data(), syntax_err() - jincpark

---

Project_Dir/srcs/builtin/built_in.c

Feat : built_in.c : error find with minseok and jincpark

---

testcodes/test_func.c

이 파일을 컴파일해서, ./a.out <directory> 형식을 사용하면, 현재 디렉토리와 변경 후 디렉토리, 변경 성공 여부를 출력합니다.

Test : ./a.out <directory> format, check chdir func

---

Project_Dir/srcs/builtin/built_in.c

echo만 들어왔을 때 생기는 sigabort 문제를 해결했습니다.

Fix : When, only "echo" Func, bt_echo make sigabort. Fix it. - tyi

---

Project_Dir/srcs/executor/executor_child.c

Feat : command not found msgs from child procs mixing up problem solved - jincpark

---

Project_Dir/Makefile
Project_Dir/includes/util.h
Project_Dir/srcs/main.c
Project_Dir/srcs/util/etc.c

인자가 1개를 초과할 때 에러메시지 출력하고 종료하도록 했습니다.

Feat : argc check - jincpark
